sudo: false
language: rust
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  # check it compiles on the latest stable compiler
  - stable
  - 1.2.0

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH


after_success:
  - travis-cargo --only stable doc
  - travis-cargo bench
  - travis-cargo coveralls --no-sudo
  - ls -la *
  - ls -la kcov/*
  - rm -rf kcov/build
  - mkdir kcov/build
  - cd kcov/build && cmake ../kcov-master && make -j
  - ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/maillurgy-*
  - ls -la kcov/build/*

cache:
  directories:
  - kcov/build/src/kcov
  - /home/travis/.cargo

matrix:
  allow_failures:
    - rust: nightly
